### ISSUE TITLE
uninitialized constant OS_VERSION (NameError)

### ISSUE THREAD

**Issue by dodekaeder** [Homebrew/linuxbrew#648] opened 2015-11-16 22:18 UTC
Hey,
just updated brew. Now I get:

``.linuxbrew/Library/Homebrew/global.rb:30:in `<top (required)>': uninitialized constant OS_VERSION (NameError)``

	from /usr/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /home/base/.linuxbrew/Library/brew.rb:15:in `<main>'

**Comment by naseer** [comment] 2015-11-16 23:22
The recent merge commit  https://github.com/Homebrew/linuxbrew/commit/85d75ac8d331564b3b9a13c6caf87ee4eca27ea5 seems to have broken this

**Comment by naseer** [comment] 2015-11-16 23:23
CC @danabrand

**Comment by danabrand** [comment] 2015-11-17 00:31
Thanks, noted, I am in transit right now, will look at this in a few hrs, if someone else wants to fix quicker, please go ahead. Thanks!

**Comment by saketkc** [comment] 2015-11-17 00:46
A quick fix:
https://github.com/Homebrew/linuxbrew/commit/e9b2f2b7bc80ac0ad745dc9b44ec6a077d3758a2#diff-12e3ebbe912ff67cc6ccc040b6fa3382L29

```diff
diff --git a/Library/Homebrew/global.rb b/Library/Homebrew/global.rb
index 54c2e36..d60e72a 100644
--- a/Library/Homebrew/global.rb
+++ b/Library/Homebrew/global.rb
@@ -26,6 +26,15 @@ else
 end
 RUBY_BIN = RUBY_PATH.dirname
 
+if RUBY_PLATFORM =~ /darwin/
+  MACOS_FULL_VERSION = `/usr/bin/sw_vers -productVersion`.chomp
+  MACOS_VERSION = MACOS_FULL_VERSION[/10\.\d+/]
+  OS_VERSION = "OS X #{MACOS_FULL_VERSION}"
+  else
+    MACOS_FULL_VERSION = MACOS_VERSION = "0"
+    OS_VERSION = RUBY_PLATFORM
+end
+

```

**Comment by danabrand** [comment] 2015-11-17 00:52
Hey thanks, i just pushed a fix in my branch (danabrand) on os.rb as I believe that's the source, but if you know this works and if anyone has access to the repo, please go ahead and push through. I actually don't have access to the main repo, just my branch and helping out during main maintainer being away (a.k.a Shaun)

**Comment by saketkc** [comment] 2015-11-17 00:58
It doesn't really fix it.

```
 brew install pkg-config
Error: uninitialized constant Checks::MacOS
Please report this bug:
    https://github.com/Homebrew/linuxbrew/blob/master/share/doc/homebrew/Troubleshooting.md#troubleshooting
/home/saket/.linuxbrew/Library/Homebrew/cmd/doctor.rb:253:in `<class:Checks>'
/home/saket/.linuxbrew/Library/Homebrew/cmd/doctor.rb:48:in `<top (required)>'
/usr/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
/usr/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
/home/saket/.linuxbrew/Library/Homebrew/cmd/install.rb:2:in `<top (required)>'
/usr/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
/usr/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
/home/saket/.linuxbrew/Library/brew.rb:72:in `require?'
/home/saket/.linuxbrew/Library/brew.rb:123:in `<main>'

```

**Comment by naseer** [comment] 2015-11-17 01:02
yeah - not fixed with https://github.com/danabrand/linuxbrew/commit/3bd7bda1b4b45d51f0e2c7487e9206666e57afa2 either

**Comment by mkinz** [comment] 2015-11-17 03:20
I am having the same problem as well.

**Comment by sjackman** [comment] 2015-11-17 03:56
@domt4 Could you please lend a hand resolving this issue, Dominyk?

**Comment by DomT4** [comment] 2015-11-17 03:56
Welp. This is punishment from somewhere for me not having a Linux box set up at the moment I'm sure. Let me just spin up a VM to check the proposed fix.

**Comment by DomT4** [comment] 2015-11-17 04:33
No dice with purely the proposed fix either. It lets `brew` be executed but:

```
brew install xz
Error: uninitialized constant Checks::MacOS
```

**Comment by saketkc** [comment] 2015-11-17 04:37
Also this: (`supernv` should not be invoked for `linuxbrew`, right?)
```
$ brew audit xyz                                                 
Error: uninitialized constant Superenv::MacOS
Please report this bug:
   
https://github.com/Homebrew/linuxbrew/blob/master/share/doc/homebrew/Troubleshooting.md#troubleshooting
/home/saket/.linuxbrew/Library/Homebrew/extend/ENV/super.rb:29:in `bin'
/home/saket/.linuxbrew/Library/Homebrew/extend/ENV.rb:7:in `superenv?'
/home/saket/.linuxbrew/Library/Homebrew/extend/ENV.rb:12:in `activate_extensions!'
/home/saket/.linuxbrew/Library/Homebrew/cmd/audit.rb:25:in `audit'
/home/saket/.linuxbrew/Library/brew.rb:146:in `<main>'
```

**Comment by saketkc** [comment] 2015-11-17 04:43
I suspect, the issue is here:
https://github.com/Homebrew/homebrew/commit/beed39e46fa021dd1c133c2c8eaaa81b524e68c7#diff-23335809c452169ea76c54df1816fb54R11

Does it not require an equivalent `require "os/linux"`?

**Comment by DomT4** [comment] 2015-11-17 04:44
Will check. If that doesn't work may have to look at reverting the last two merges to buy us some time to actually work on this rather than running around screaming. Maybe it's just me running around screaming :wink:.

**Comment by DomT4** [comment] 2015-11-17 04:48
No dice. You can't actually `require "os/linux"` because it's a directory. Would have to `require "os/linux/hardware"`, which doesn't fix the issue apparently.

**Comment by danabrand** [comment] 2015-11-17 05:03
@DomT4 Can you please revert as suggested to previous version before this morning's commit? I am back online now.

**Comment by DomT4** [comment] 2015-11-17 05:04
Just checking a hunch first. If the hunch is right, great. If not, will go on a reverting merge commits spree.

**Comment by DomT4** [comment] 2015-11-17 05:08
Revert done. The error is being thrown from the `doctor` command as noted by @saketkc. Wondering if the error resides in there and chunks of things need to be wrapped in `if OS.mac?` logic in Linuxbrew :confused:.

**Comment by DomT4** [comment] 2015-11-17 05:10
If `brew update` doesn't work you'll need to run:

```bash
git fetch && git reset --hard origin/master
```
Inside your Linuxbrew install to get `brew` functional again. Hopefully not many people updated over the last few hours. Sorry about this folks.

**Comment by ryanjafari** [comment] 2015-11-17 05:12
Works thanks guys!

**Comment by danabrand** [comment] 2015-11-17 05:19
Thank you so much Dominyk. Mistake was mine for not testing more thoroughly.

**Comment by DomT4** [comment] 2015-11-17 05:23
No worries. These things happen Dana. Most of the Homebrew maintainers have broken Homebrew dramatically at least once, so you're not alone heh.

**Comment by rwhogg** [comment] 2015-11-17 05:25
I'm personally really impressed that it was only broken for a few hours. Great teamwork getting it back up and running again so soon :smile:

**Comment by danabrand** [comment] 2015-11-17 05:34
Heh, you guys are fun - I feel part of the team now :-) On a serious note, I will garden through the `doctor` code and propose a patch that maybe you can test as well before attempting a commit. Or just wait for Shaun to get back, I was only worried about Linuxbrew starting to lag quite a bit behind Homebrew. Thanks again.

**Comment by sjackman** [comment] 2015-11-17 05:53
Thanks for rallying, friends. Nothing like calamity to bring a team together. =)
There's no need to wait for my return. Please do steam ahead in my absence. Having two people test and sign off on the merge is a good idea.

**Comment by xu-cheng** [comment] 2015-11-25 05:52
The root of the problem is Homebrew's OS abstraction is not good enough, and Linuxbrew uses too many hacks instead of proper abstraction.

Until I figure out better OS abstraction on Homebrew end and move all linux specific codes to `os/linux.rb`, you can temporary workaround the problem by `require "os/mac"` unconditionally.

**Comment by danabrand** [comment] 2015-11-25 17:20
@xu-cheng Thank you - will do that, test out and push in my branch. After work hours today though, which means about 6 hrs from now.

**Comment by DomT4** [comment] 2015-11-30 18:38
Should be resolved.

**Closed by DomT4** 2015-11-30 18:38 UTC
Labels: bug

**Comment by sjackman** [comment] 2016-01-06 03:38
See https://github.com/Homebrew/linuxbrew/issues/600#issuecomment-169105973 for how I've resolved these reverted merge commits.
