### ISSUE TITLE
`brew install git` on a machine with no git tries to git clone taps

### ISSUE THREAD

**Issue by jepio** [Homebrew/linuxbrew#471] opened 2015-07-09 13:59 UTC
I installed linuxbrew on a machine that does not have git. During the installation the fallback solution to cloning the repository was curl'ing the tarball. After linuxbrew was ready I did `brew doctor` and got:

    Please note that these warnings are just used to help the Homebrew maintainers
    with debugging if you file an issue. If everything you use Homebrew for is
    working fine: please don't worry and just ignore them. Thanks!
    
    Warning: Git could not be found in your PATH.
    Homebrew uses Git for several internal functions, and some formulae use Git
    checkouts instead of stable tarballs. You may want to install Git:
      brew install git

Next I proceed to `brew install git -v`, but this time there's no fallback:

    ==> Tapping homebrew/dupes
    git clone https://github.com/Homebrew/homebrew-dupes /home/chroottest/.linuxbrew/Library/Taps/homebrew/homebrew-dupes --depth=1
    You must: brew install git
    Error: Failure while executing: git clone https://github.com/Homebrew/homebrew-dupes /home/chroottest/.linuxbrew/Library/Taps/homebrew/homebrew-dupes --depth=1

I think brew should (atleast for installing git) check whether it already exists, if not fallback to the curl method of acquiring the taps.

**Comment by iggyvolz** [comment] 2015-07-09 17:03
Dupe of #435.  Do brew install git --without-tcl-tk or install git first.

**Comment by sjackman** [comment] 2015-07-09 18:04
We have a few options.

1. Make --without-tcl-tk the default i.e. `depends_on "tcl-tk" => :optional`
2. Make --without-tcl-tk the default if git is not found in the PATH
3. Add tcl-tk to Homebrew/linuxbrew

**Closed by sjackman** 2015-07-09 18:04 UTC
Labels: build-error
