### ISSUE TITLE
Pip no longer works

### ISSUE THREAD

**Issue by nemith** [Homebrew/linuxbrew#450] opened 2015-06-23 09:39 UTC
After upgrading python pip no longer works.  Blew away any old versions and reinstalled python with linuxbrew and still have the same issue

```
Traceback (most recent call last):
    File "/data/users/bbennett/linuxbrew/bin/pip", line 9, in <module>
      load_entry_point('pip==7.0.3', 'console_scripts', 'pip')()
    File "build/bdist.linux-x86_64/egg/pkg_resources/__init__.py", line 558, in load_entry_point
    File "build/bdist.linux-x86_64/egg/pkg_resources/__init__.py", line 2682, in load_entry_point
    File "build/bdist.linux-x86_64/egg/pkg_resources/__init__.py", line 2355, in load
    File "build/bdist.linux-x86_64/egg/pkg_resources/__init__.py", line 2361, in resolve
    File "/data/users/bbennett/linuxbrew/Cellar/python/2.7.10/lib/python2.7/site-packages/pip-7.0.3-py2.7.egg/pip/__init__.py", line 15, in <module>
      from pip.vcs import git, mercurial, subversion, bazaar  # noqa
    File "/data/users/bbennett/linuxbrew/Cellar/python/2.7.10/lib/python2.7/site-packages/pip-7.0.3-py2.7.egg/pip/vcs/subversion.py", line 9, in <module>
      from pip.index import Link
    File "/data/users/bbennett/linuxbrew/Cellar/python/2.7.10/lib/python2.7/site-packages/pip-7.0.3-py2.7.egg/pip/index.py", line 30, in <module>
      from pip.wheel import Wheel, wheel_ext
    File "/data/users/bbennett/linuxbrew/Cellar/python/2.7.10/lib/python2.7/site-packages/pip-7.0.3-py2.7.egg/pip/wheel.py", line 35, in <module>
      from pip._vendor.distlib.scripts import ScriptMaker
    File "/data/users/bbennett/linuxbrew/Cellar/python/2.7.10/lib/python2.7/site-packages/pip-7.0.3-py2.7.egg/pip/_vendor/__init__.py", line 92, in load_module
      raise ImportError("No module named '%s'" % (name,))
  ImportError: No module named 'pip._vendor.distlib.scripts'
```

**Comment by nemith** [comment] 2015-06-23 10:27
Could be related to this change.

https://github.com/BrewTestBot/homebrew/commit/e3920dca3eda7851fad79c48edc0bd9c4f168264

**Comment by nemith** [comment] 2015-06-23 14:13
It also seems that readline is not being properly linked either.  

```
[bbennett@dev856 /data/users/bbennett/fbcode-hg/tupperware/config] python
Python 2.7.10 (default, Jun 23 2015, 05:34:38) 
[GCC 4.4.7 20120313 (Red Hat 4.4.7-11)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import readline
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named readline
```

**Comment by sjackman** [comment] 2015-06-23 23:38
The installation of Python has proven to be very fragile in the past (usually with `openssl`), and I'm that I don't have the time to help you trouble shoot it. I hope you're able to sort it out. If you find a fix or workaround, please post it here. Good luck, Brandon!

**Comment by iggyvolz** [comment] 2015-06-24 02:20
Installing python works for me on my Ubuntu 15.04 server - what specs are you using?

You could try removing the commit from history and see if it installs - if so then that's the source of it:
```bash
cd $(brew --prefix)
git rebase -i 5a35942 ## Delete the line "80c83ab python: fix openssl on 10.11" when this opens up
brew install python
git pull --force ## Force-undo the changes
```

**Comment by tdsmith** [comment] 2015-06-24 03:26
Can you `import _ssl`?

**Comment by nemith** [comment] 2015-06-24 11:13
@iggyvolz 
CentOS 6.4 here.

Reverting that change didn't actually help.  


@tdsmith Nope.

```
[bbennett@dev856 ~] python
Python 2.7.10 (default, Jun 23 2015, 05:34:38) 
[GCC 4.4.7 20120313 (Red Hat 4.4.7-11)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import _ssl
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named _ssl
>>> import ssl
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/data/users/bbennett/linuxbrew/Cellar/python/2.7.10/lib/python2.7/ssl.py", line 97, in <module>
    import _ssl             # if we can't import it, let the error propagate
ImportError: No module named _ssl
>>> 
```

**Comment by sjackman** [comment] 2015-06-24 22:06
One workaround is to copy the file `_ssl.so` from a working installation to
`~/.linuxbrew/Cellar/python/2.7.10/lib/python2.7/lib-dynload/_ssl.so`.

**Comment by sjackman** [comment] 2015-06-24 22:07
See #188 and https://github.com/Homebrew/linuxbrew/issues/420#issuecomment-110808474 for the workaround.

**Comment by sjackman** [comment] 2015-06-24 22:08
I think this issue is a duplicate of #420. Let's move the discussion there.

**Closed by sjackman** 2015-06-24 22:08 UTC
Labels: build-error, help wanted
