### ISSUE TITLE
Blast Build Failure

### ISSUE THREAD

**Issue by LeeBergstrand** [Homebrew/linuxbrew#475] opened 2015-07-10 18:10 UTC
```shell
lee2@bm-z820:~$ brew install blast
==> Installing blast from homebrew/homebrew-science
==> Downloading ftp://ftp.ncbi.nlm.nih.gov/blast/executables/blast+/2.2.31/ncbi-blast-2.2.31+-src.tar.gz
Already downloaded: /home/lee2/.cache/Homebrew/blast-2.2.31.tar.gz
==> Patching
patching file c++/include/corelib/ncbimtx.inl
==> ./configure --prefix=/home/lee2/.linuxbrew/Cellar/blast/2.2.31 --libdir=/home/lee2/.linuxbrew/Cellar/blast/2.2.31/libexec --without-debug --with-mt --without-mysql --without-freetype --without-g
==> make
make[2]: *** [all_r.real] Error 5
make[2]: Leaving directory `/tmp/blast20150710-27069-bi9wf7/ncbi-blast-2.2.31+-src/c++/ReleaseMT/build/algo'
make[1]: *** [all_r.real] Error 5
make[1]: Leaving directory `/tmp/blast20150710-27069-bi9wf7/ncbi-blast-2.2.31+-src/c++/ReleaseMT/build'
make: *** [all] Error 2

READ THIS: https://github.com/Homebrew/linuxbrew/blob/master/share/doc/homebrew/Troubleshooting.md#troubleshooting
```

`brew gist-logs blast` ==> https://gist.github.com/fd9ed15e2d185b2a6389

```shell
lee2@bm-z820:~$ brew config
HOMEBREW_VERSION: 0.9.5
ORIGIN: https://github.com/Homebrew/linuxbrew
HEAD: 56d088f9f9e89bad3455db022b8fcac1e842009e
Last commit: 39 minutes ago
HOMEBREW_PREFIX: /home/lee2/.linuxbrew
HOMEBREW_CELLAR: /home/lee2/.linuxbrew/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://linuxbrew.bintray.com
CPU: 32-core 64-bit 6
OS X: 0-x86_64
Xcode: N/A
CLT: N/A
Clang: N/A
X11: N/A
System Ruby: 1.9.3-p484 => /usr/bin/ruby1.9.1
Perl: /usr/bin/perl
Python: /usr/bin/python => /usr/bin/python2.7
Ruby: /usr/bin/ruby => /usr/bin/ruby1.9.1
Java: 1.7.0_79
```

Error Code from Log.

```
make[6]: Entering directory `/tmp/blast20150710-27069-bi9wf7/ncbi-blast-2.2.31+-src/c++/ReleaseMT/build/algo/blast/unit_tests/api'
/usr/bin/g++-4.8  -std=gnu++11 -c  -Wall -Wno-format-y2k  -pthread -fopenmp -Os -w -pipe -march=core2 -fPIC   -DNCBI_MODULE=BLAST -DNDEBUG -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -D_LARGEFILE64_SOURCE  -isystem/home/lee2/.linuxbrew/include -D_MT -D_REENTRANT -D_THREAD_SAFE -I/tmp/blast20150710-27069-bi9wf7/ncbi-blast-2.2.31+-src/c++/ReleaseMT/inc -I/tmp/blast20150710-27069-bi9wf7/ncbi-blast-2.2.31+-src/c++/include  -Wno-unused-local-typedefs -I/tmp/blast20150710-27069-bi9wf7/ncbi-blast-2.2.31+-src/c++/src/algo/blast/unit_tests/api/../../api /tmp/blast20150710-27069-bi9wf7/ncbi-blast-2.2.31+-src/c++/src/algo/blast/unit_tests/api/aalookup_unit_test.cpp -o aalookup_unit_test.o 
/usr/bin/g++-4.8  -std=gnu++11 -Wl,-rpath,/usr/lib/gcc/x86_64-linux-gnu/4.8/../../../x86_64-linux-gnu -Wl,--enable-new-dtags -Wl,-export-dynamic  -pthread -fopenmp -L/home/lee2/.linuxbrew/lib -Wl,-rpath,/home/lee2/.linuxbrew/lib  -O  aalookup_unit_test.o   -Wl,-rpath,/home/lee2/.linuxbrew/Cellar/blast/2.2.31/libexec -Wl,-rpath-link,/tmp/blast20150710-27069-bi9wf7/ncbi-blast-2.2.31+-src/c++/ReleaseMT/lib -L/tmp/blast20150710-27069-bi9wf7/ncbi-blast-2.2.31+-src/c++/ReleaseMT/lib -lblast_unit_test_util -ltest_boost -lxblast -lxalgoblastdbindex -lcomposition_adjustment -lxalgodustmask -lxalgowinmask -lseqmasks_io -lseqdb -lblast_services -lxobjutil -lxobjread -lvariation -lcreaders -lsubmit -lxnetblastcli -lxnetblast -lblastdb -lscoremat -ltables -lxalnmgr -lxobjsimple -lncbi_xloader_genbank-dll -lncbi_xreader_id1-dll -lncbi_xreader_id2-dll -lncbi_xreader_cache-dll -lxconnect -ldbapi_driver -lncbi_xreader-dll -lxconnect -lid1 -lid2 -lseqsplit -lxcompress -lxobjmgr -lgenome_collection -lseqedit -lseqset -lseq -lseqcode -lsequtil -lpub -lmedline -lbiblio -lgeneral -lxser -lxutil -lxncbi -lnsl -lz  -lbz2   -ldl -ldl -lm  -lpthread -o aalookup_unit_test 
/tmp/blast20150710-27069-bi9wf7/ncbi-blast-2.2.31+-src/c++/ReleaseMT/lib/libncbi_xreader-dll.so: undefined reference to `ncbi::CObjectInfo::ReadContainer(ncbi::CObjectIStream&, ncbi::CReadContainerElementHook&)'
/tmp/blast20150710-27069-bi9wf7/ncbi-blast-2.2.31+-src/c++/ReleaseMT/lib/libncbi_xreader-dll.so: undefined reference to `ncbi::CCompressionStream::~CCompressionStream()'
/tmp/blast20150710-27069-bi9wf7/ncbi-blast-2.2.31+-src/c++/ReleaseMT/lib/libncbi_xreader-dll.so: undefined reference to `ncbi::CCompressionStream::~CCompressionStream()'
/tmp/blast20150710-27069-bi9wf7/ncbi-blast-2.2.31+-src/c++/ReleaseMT/lib/libncbi_xreader-dll.so: undefined reference to `typeinfo for ncbi::CCompressionStreamProcessor'
/tmp/blast20150710-27069-bi9wf7/ncbi-blast-2.2.31+-src/c++/ReleaseMT/lib/libncbi_xreader-dll.so: undefined reference to `virtual thunk to ncbi::CCompressionStream::~CCompressionStream()'
/tmp/blast20150710-27069-bi9wf7/ncbi-blast-2.2.31+-src/c++/ReleaseMT/lib/libncbi_xreader-dll.so: undefined reference to `ncbi::CNlmZipReader::CNlmZipReader(ncbi::IReader*, int, ncbi::CNlmZipReader::EHeader)'
/tmp/blast20150710-27069-bi9wf7/ncbi-blast-2.2.31+-src/c++/ReleaseMT/lib/libncbi_xreader-dll.so: undefined reference to `ncbi::CCompressionStreamProcessor::CCompressionStreamProcessor(ncbi::CCompressionProcessor*, ncbi::CCompressionStreamProcessor::EDeleteProcessor, long, long)'
/tmp/blast20150710-27069-bi9wf7/ncbi-blast-2.2.31+-src/c++/ReleaseMT/lib/libncbi_xreader-dll.so: undefined reference to `typeinfo for ncbi::CCompressionStream'
/tmp/blast20150710-27069-bi9wf7/ncbi-blast-2.2.31+-src/c++/ReleaseMT/lib/libncbi_xreader-dll.so: undefined reference to `ncbi::CCompressionStreamProcessor::~CCompressionStreamProcessor()'
/tmp/blast20150710-27069-bi9wf7/ncbi-blast-2.2.31+-src/c++/ReleaseMT/lib/libncbi_xreader-dll.so: undefined reference to `ncbi::CZipDecompressor::CZipDecompressor(int, unsigned int)'
/tmp/blast20150710-27069-bi9wf7/ncbi-blast-2.2.31+-src/c++/ReleaseMT/lib/libncbi_xreader-dll.so: undefined reference to `ncbi::CZipCompressor::CZipCompressor(ncbi::ICompression::ELevel, int, int, int, unsigned int)'
/tmp/blast20150710-27069-bi9wf7/ncbi-blast-2.2.31+-src/c++/ReleaseMT/lib/libncbi_xreader-dll.so: undefined reference to `ncbi::CCompressionStream::CCompressionStream(std::basic_ios<char, std::char_traits<char> >&, ncbi::CCompressionStreamProcessor*, ncbi::CCompressionStreamProcessor*, int)'
/tmp/blast20150710-27069-bi9wf7/ncbi-blast-2.2.31+-src/c++/ReleaseMT/lib/libncbi_xreader-dll.so: undefined reference to `virtual thunk to ncbi::CCompressionStream::~CCompressionStream()'
/tmp/blast20150710-27069-bi9wf7/ncbi-blast-2.2.31+-src/c++/ReleaseMT/lib/libncbi_xreader-dll.so: undefined reference to `ncbi::CCompressionStream::Finalize(ncbi::CCompressionStream::EDirection)'
/tmp/blast20150710-27069-bi9wf7/ncbi-blast-2.2.31+-src/c++/ReleaseMT/lib/libncbi_xreader-dll.so: undefined reference to `ncbi::CCompressionStream::~CCompressionStream()'
collect2: error: ld returned 1 exit status
make[6]: *** [aalookup_unit_test] Error 1
make[6]: Leaving directory `/tmp/blast20150710-27069-bi9wf7/ncbi-blast-2.2.31+-src/c++/ReleaseMT/build/algo/blast/unit_tests/api'
FAILED: src/algo/blast/unit_tests/api/Makefile.aalookup_unit_test.app
make[6]: Entering directory `/tmp/blast20150710-27069-bi9wf7/ncbi-blast-2.2.31+-src/c++/ReleaseMT/build/algo/blast/unit_tests/api'
/bin/rm -f aalookup_unit_test .aalookup_unit_test.stamp
make[6]: Leaving directory `/tmp/blast20150710-27069-bi9wf7/ncbi-blast-2.2.31+-src/c++/ReleaseMT/build/algo/blast/unit_tests/api'
make[5]: *** [all.nonusr] Error 2
make[5]: Leaving directory `/tmp/blast20150710-27069-bi9wf7/ncbi-blast-2.2.31+-src/c++/ReleaseMT/build/algo/blast/unit_tests/api'
make[4]: *** [all_r.real] Error 5
make[4]: Leaving directory `/tmp/blast20150710-27069-bi9wf7/ncbi-blast-2.2.31+-src/c++/ReleaseMT/build/algo/blast/unit_tests'
make[3]: *** [all_r.real] Error 5
make[3]: Leaving directory `/tmp/blast20150710-27069-bi9wf7/ncbi-blast-2.2.31+-src/c++/ReleaseMT/build/algo/blast'
make[2]: *** [all_r.real] Error 5
make[2]: Leaving directory `/tmp/blast20150710-27069-bi9wf7/ncbi-blast-2.2.31+-src/c++/ReleaseMT/build/algo'
make[1]: *** [all_r.real] Error 5
make[1]: Leaving directory `/tmp/blast20150710-27069-bi9wf7/ncbi-blast-2.2.31+-src/c++/ReleaseMT/build'
make: *** [all] Error 2
```

**Comment by LeeBergstrand** [comment] 2015-07-10 18:11
May be related to: https://github.com/Homebrew/linuxbrew/issues/473

**Comment by sjackman** [comment] 2015-07-10 18:18
Do you have any other NCBI formulas installed, and if so, can you check if they have any libraries installed in `/lib`?

**Comment by LeeBergstrand** [comment] 2015-07-10 18:27
I am currently working on a sever with BLAST 2.2.28 already apt-get installed (which people wish to not update through). So I'm basically linux brewing over that.

```shell
lee2@bm-z820:/lib$ brew list
boost  bzip2  expat  jpeg  libpng  pcre  tcl-tk  xz
```

```shell
lee2@bm-z820:/lib$ ls /lib
apparmor  firmware  init                                  libip4tc.so.0.1.0  libiptc.so.0      libxtables.so.10.0.0  modprobe.d      recovery-mode  terminfo  x86_64-linux-gnu
cpp       hdparm    klibc-P2s_k-gf23VtrGgO2_4pGkQgwMY.so  libip6tc.so.0      libiptc.so.0.0.0  linux-sound-base      modules-load.d  resolvconf     udev      xtables
crda      ifupdown  libip4tc.so.0                         libip6tc.so.0.1.0  libxtables.so.10  lsb                   plymouth        systemd        ufw
```

**Comment by sjackman** [comment] 2015-07-10 20:23
Can you check whether that apt-get installed package also installs libraries? If so, you may be able to work around this issue by using the [Standalone installation](https://github.com/Homebrew/linuxbrew/wiki/Standalone-Installation) instructions for Linuxbrew.

**Comment by sjackman** [comment] 2015-10-15 19:35
Duplicate of https://github.com/Homebrew/homebrew-science/issues/2705

**Closed by sjackman** 2015-10-15 19:35 UTC
Labels: build-error
