### ISSUE TITLE
Using Linuxbrew with ARM processor

### ISSUE THREAD

**Issue by wickedsp1d3r** [Homebrew/linuxbrew#112] opened 2014-08-06 06:11 UTC
Hello there,

I got Linuxbrew installed, but `brew install <formula>` gives me:
```
Sorry, Homebrew does not support your computer's CPU architecture. For PPC support, see https://github.com/mistydemeo/tigerbrew.
```
`uname -a` gives me:
```
Linux Jolla 3.4.91.20140612.1 #1 SMP PREEMPT Mon Jun 16 17:24:16 UTC 2014 armv71 armv71 armv71 GNU/Linux.
```
And cat /proc/cpuinfo:
```
Processor			ARMv7 Processor rev 4 (v71)
Processor			0
```
Is there anything I can do to get Linuxbrew working on my system? Thank you for your time.

**Comment by billp** [comment] 2015-02-18 17:08
Are there any news for support for armv7? Raspberry Pi 2 is available (armv7, 4 cores) and I thing this feature is a must

**Comment by Mikaela** [comment] 2015-02-18 17:23
Being unaware of this issue, I opened https://github.com/Homebrew/linuxbrew/issues/260 24 days ago which was closed 19 days ago and it seems to be duplicate of this one.

**Comment by sjackman** [comment] 2015-02-25 05:45
I won't be adding ARM support myself, because I have no ARM hardware on which to test it. I will merge a pull request to add support for ARM to Linuxbrew provided that a couple people can vouch that it works.

**Comment by Sean1708** [comment] 2015-05-25 16:52
Just out of interest, what changes would be needed to support ARM?

**Comment by sjackman** [comment] 2015-05-26 00:17
Homebrew (not Linuxbrew) supports PPC and Intel. [Search `Library/Homebrew` for `ppc`](https://github.com/Homebrew/linuxbrew/search?utf8=%E2%9C%93&q=ppc+path%3ALibrary%2FHomebrew&type=Code) and you'll probably find most of the locations that need to be changed. It's probably doable with some effort.

**Comment by sjackman** [comment] 2015-07-19 06:38
I've add ARM support to Linuxbrew for the Raspberry Pi. Happy hacking! I have a Raspberry Pi myself now.
See 2077229dfdcc32559c80349080d8baf345ef42b9

**Closed** 2015-07-19 06:39 UTC
