### ISSUE TITLE
RPi install error for openssl - can't find split

### ISSUE THREAD

**Issue by walchko** [Homebrew/linuxbrew#563] opened 2015-09-20 14:18 UTC
I just installed linuxbrew on RPi (Raspbian wheezy) and when I try to install openssl, I get this error:

``` bash
pi@hypnotoad ~ $ brew update
Already up-to-date.
pi@hypnotoad ~ $ brew install openssl
==> Downloading https://www.openssl.org/source/openssl-1.0.2d.tar.gz
Already downloaded: /home/pi/.cache/Homebrew/openssl-1.0.2d.tar.gz
tar: A lone zero block at 52140
Error: undefined method `split' for nil:NilClass
Please report this bug:
    https://github.com/Homebrew/linuxbrew/blob/master/share/doc/homebrew/Troubleshooting.md#troubleshooting
/home/pi/.linuxbrew/Library/Homebrew/os/linux/hardware.rb:53:in `flags'
/home/pi/.linuxbrew/Library/Homebrew/os/linux/hardware.rb:63:in `block (2 levels) in <module:LinuxCPUs>'
/home/pi/.linuxbrew/Library/Homebrew/os/mac.rb:171:in `prefer_64_bit?'
/home/pi/.linuxbrew/Library/Formula/openssl.rb:53:in `install'
/home/pi/.linuxbrew/Library/Homebrew/build.rb:129:in `block in install'
/home/pi/.linuxbrew/Library/Homebrew/formula.rb:682:in `block in brew'
/home/pi/.linuxbrew/Library/Homebrew/formula.rb:1098:in `block in stage'
/home/pi/.linuxbrew/Library/Homebrew/resource.rb:91:in `block in unpack'
/home/pi/.linuxbrew/Library/Homebrew/extend/fileutils.rb:16:in `mktemp'
/home/pi/.linuxbrew/Library/Homebrew/resource.rb:88:in `unpack'
/home/pi/.linuxbrew/Library/Homebrew/resource.rb:81:in `stage'
/home/pi/.linuxbrew/Library/Homebrew/formula.rb:1090:in `stage'
/home/pi/.linuxbrew/Library/Homebrew/formula.rb:678:in `brew'
/home/pi/.linuxbrew/Library/Homebrew/build.rb:107:in `install'
/home/pi/.linuxbrew/Library/Homebrew/build.rb:179:in `<main>'
pi@hypnotoad ~ $ brew gist-logs openssl
Error: No logs.
```

Here is some system info:
```bash
pi@hypnotoad ~ $ uname -a
Linux hypnotoad 4.1.6-v7+ #810 SMP PREEMPT Tue Aug 18 15:32:12 BST 2015 armv7l GNU/Linux
pi@hypnotoad ~ $ brew doctor
Your system is ready to brew.
pi@hypnotoad ~ $ ruby -v
ruby 1.9.3p194 (2012-04-20 revision 35410) [arm-linux-eabihf]
```

**Comment by dunn** [comment] 2015-09-21 02:37
May be occurring here: https://github.com/Homebrew/linuxbrew/blob/master/Library/Homebrew/os/linux/hardware.rb#L53

Does `/proc/cpuinfo` exist on your system?

**Comment by walchko** [comment] 2015-09-21 03:23
yes, sorry I am not much of a *ruby guy*, so is this splitting a string or something? I don't see anything in the output below that talks about `flags` either.

``` bash
pi@hypnotoad ~ $ more /proc/cpuinfo
processor	: 0
model name	: ARMv7 Processor rev 5 (v7l)
BogoMIPS	: 38.40
Features	: half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt 
vfpd32 lpae evtstrm 
CPU implementer	: 0x41
CPU architecture: 7
CPU variant	: 0x0
CPU part	: 0xc07
CPU revision	: 5

processor	: 1
model name	: ARMv7 Processor rev 5 (v7l)
BogoMIPS	: 38.40
Features	: half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt 
vfpd32 lpae evtstrm 
CPU implementer	: 0x41
CPU architecture: 7
CPU variant	: 0x0
CPU part	: 0xc07
CPU revision	: 5

processor	: 2
model name	: ARMv7 Processor rev 5 (v7l)
BogoMIPS	: 38.40
Features	: half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt 
vfpd32 lpae evtstrm 
CPU implementer	: 0x41
CPU architecture: 7
CPU variant	: 0x0
CPU part	: 0xc07
CPU revision	: 5

processor	: 3
model name	: ARMv7 Processor rev 5 (v7l)
BogoMIPS	: 38.40
Features	: half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt 
vfpd32 lpae evtstrm 
CPU implementer	: 0x41
CPU architecture: 7
CPU variant	: 0x0
CPU part	: 0xc07
CPU revision	: 5

Hardware	: BCM2709
Revision	: a21041
Serial		: 0000000063848a3a
```

**Comment by walchko** [comment] 2015-09-21 14:48
I tried changing that line and so far it *seems* to work on my RPi2 (armv7)

```ruby
  def flags
    @flags ||= cpuinfo[/^Features.*/, 0].split
  end
```

I double checked on my older RPi(armv6) and it also doesn't have `flags` either:

```bash
pi@calculon ~ $ more /proc/cpuinfo 
processor	: 0
model name	: ARMv6-compatible processor rev 7 (v6l)
BogoMIPS	: 2.00
Features	: half thumb fastmult vfp edsp java tls 
CPU implementer	: 0x41
CPU architecture: 7
CPU variant	: 0x0
CPU part	: 0xb76
CPU revision	: 7

Hardware	: BCM2708
Revision	: 0002
Serial		: 000000008e0a5a17
```

**Comment by dunn** [comment] 2015-09-22 01:12
Afraid I don't know enough about Linux to help more, gonna have to pass you on to @sjackman

**Comment by sjackman** [comment] 2015-10-03 06:05
Thanks for the bug report. It looks like the line should be
```ruby
@flags ||= cpuinfo[/^(flags|Features).*/, 0].split
```

**Comment by sjackman** [comment] 2015-10-03 06:06
I haven't fired up my Raspberry Pi in a while, but when I do, I'll test this out.

**Comment by sjackman** [comment] 2015-10-03 19:47
Duplicate of #518

**Closed by sjackman** 2015-10-03 19:47 UTC
Labels: bug

**Comment by ronanc-raspberrypi** [comment] 2015-10-04 17:48
sjackman comment Oct 3, 2015
iv'e just tried it and it works on arm7l (raspberry pi 2),
see issue 
https://github.com/Homebrew/linuxbrew/issues/581#issuecomment-145368911
thanks

**Comment by ronanc-raspberrypi** [comment] 2015-10-05 03:26
Note on the above, 

after modifying the hardware.rb file, the next time i 'brew doctor' i get a warning: you have uncommited modifications to Homebrew..........should you later need to do so for some reason.
    cd /home/pi.linuxbrew/Library && git stash && git clean -d -f

Ok Fair enough, if i read the message carefully i would not have stashed and cleaned. because it reverts the file back to the unmodified version.
