### ISSUE TITLE
Subversion 1.9.3 installation error

### ISSUE THREAD

**Issue by clayshieh** [Homebrew/linuxbrew#693] opened 2015-12-29 08:19 UTC
From:
https://github.com/Homebrew/homebrew/issues/47465#issuecomment-167742992
I have already modified my local subversion.rb file with the new url's and correct sha256 so that it will install 1.9.3 instead. But now I'm getting an error:

scons: Reading SConscript files ...
/bin/sh: 1: /usr: Permission denied
OSError: '/usr --cflags gssapi' exited 126:
  File "/tmp/subversion--serf20151228-82007-1qk8zj6/serf-1.3.8/SConstruct", line 360:
    env.ParseConfig('$GSSAPI --cflags gssapi')
  File "/home/clayshieh/.linuxbrew/Cellar/scons/2.4.1/libexec/scons-local/SCons/Environment.py", line 1576:
    return function(self, self.backtick(command))
  File "/home/clayshieh/.linuxbrew/Cellar/scons/2.4.1/libexec/scons-local/SCons/Environment.py", line 594:
    raise OSError("'%s' exited %d" % (command, status))

seems to be the same error as the issue #665.
Any help?

**Comment by sjackman** [comment] 2015-12-29 22:28
Duplicate of #665

**Closed by sjackman** 2015-12-29 22:28 UTC
