### ISSUE TITLE
 brew help Command - error in Ubuntu 14.04

### ISSUE THREAD

**Issue by kholmatov** [Homebrew/linuxbrew#652] opened 2015-11-17 02:53 UTC
brew help
/root/.linuxbrew/Library/Homebrew/global.rb:30:in `<top (required)>': uninitialized constant OS_VERSION (NameError)
	from /usr/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
	from /usr/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
	from /root/.linuxbrew/Library/brew.rb:15:in `<main>'
Please help, how fix this problem?

**Comment by erictleung** [comment] 2015-11-17 03:03
Appears to be a duplicate of #648

**Comment by DomT4** [comment] 2015-11-17 04:02
Working on it.

**Closed** 2015-11-17 04:03 UTC

**Comment by DomT4** [comment] 2015-11-17 05:11
If `brew update` doesn't work you'll need to run:

```bash
git fetch && git reset --hard origin/master
```
Inside your Linuxbrew install to get `brew` functional again. Hopefully not many people updated over the last few hours. Sorry about this folks.
