### ISSUE TITLE
sqlite formula not working

### ISSUE THREAD

**Issue by ocehugo** [Homebrew/linuxbrew#407] opened 2015-05-14 02:53 UTC
I'm getting 

`sqlite3.o: file not recognized: File truncated`

when building sqlite.

```
 gcc --version
gcc (GCC) 4.4.7 20120313 (Red Hat 4.4.7-11)
Copyright (C) 2010 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

**Comment by sjackman** [comment] 2015-05-14 15:51
Please report `brew gist-logs sqlite` and read https://github.com/Homebrew/linuxbrew/wiki/Troubleshooting

**Comment by naseer** [comment] 2015-05-14 19:37
I have the same problem - gist - https://gist.github.com/anonymous/67f9bb34c4d9cd1502d7

**Comment by sjackman** [comment] 2015-05-15 17:05
https://gist.github.com/anonymous/dcec5ec575a0dc9348c8#file-02-make-L9-L14
```
libtool: compile:  /local/mnt/workspace/naseer/.linuxbrew/bin/gcc-4.9 -DPACKAGE_NAME=\"sqlite\" -DPACKAGE_TARNAME=\"sqlite\" -DPACKAGE_VERSION=\"3.8.10.1\" "-DPACKAGE_STRING=\"sqlite 3.8.10.1\"" -DPACKAGE_BUGREPORT=\"http://www.sqlite.org\" -DPACKAGE_URL=\"\" -DPACKAGE=\"sqlite\" -DVERSION=\"3.8.10.1\" -DSTDC_HEADERS=1 -DHAVE_SYS_TYPES_H=1 -DHAVE_SYS_STAT_H=1 -DHAVE_STDLIB_H=1 -DHAVE_STRING_H=1 -DHAVE_MEMORY_H=1 -DHAVE_STRINGS_H=1 -DHAVE_INTTYPES_H=1 -DHAVE_STDINT_H=1 -DHAVE_UNISTD_H=1 -DHAVE_DLFCN_H=1 -DLT_OBJDIR=\".libs/\" -DHAVE_FDATASYNC=1 -DHAVE_USLEEP=1 -DHAVE_LOCALTIME_R=1 -DHAVE_GMTIME_R=1 -DHAVE_DECL_STRERROR_R=1 -DHAVE_STRERROR_R=1 -DHAVE_READLINE=1 -DHAVE_POSIX_FALLOCATE=1 -I. -isystem/local/mnt/workspace/naseer/.linuxbrew/include -DSQLITE_ENABLE_RTREE -DSQLITE_ENABLE_COLUMN_METADATA -D_REENTRANT=1 -DSQLITE_THREADSAFE=1 -DSQLITE_ENABLE_FTS3 -DSQLITE_ENABLE_RTREE -Os -w -pipe -march=core2 -c sqlite3.c -o sqlite3.o >/dev/null 2>&1
/bin/sh ./libtool --tag=CC   --mode=link /local/mnt/workspace/naseer/.linuxbrew/bin/gcc-4.9 -D_REENTRANT=1 -DSQLITE_THREADSAFE=1  -DSQLITE_ENABLE_FTS3 -DSQLITE_ENABLE_RTREE -Os -w -pipe -march=core2  -L/local/mnt/workspace/naseer/.linuxbrew/lib -Wl,-rpath,/local/mnt/workspace/naseer/.linuxbrew/lib -o sqlite3 shell.o sqlite3.o -lreadline -lcurses  -ldl -lpthread 
libtool: link: /local/mnt/workspace/naseer/.linuxbrew/bin/gcc-4.9 -D_REENTRANT=1 -DSQLITE_THREADSAFE=1 -DSQLITE_ENABLE_FTS3 -DSQLITE_ENABLE_RTREE -Os -w -pipe -march=core2 -Wl,-rpath -Wl,/local/mnt/workspace/naseer/.linuxbrew/lib -o sqlite3 shell.o sqlite3.o  -L/local/mnt/workspace/naseer/.linuxbrew/lib -lreadline -lcurses -ldl -lpthread
sqlite3.o: file not recognized: File truncated
collect2: error: ld returned 1 exit status
make: *** [sqlite3] Error 1
```

**Comment by sjackman** [comment] 2015-05-15 17:09
So weird. I am able to reproduce this issue. Oddly it built just fine for me on 2015-05-11, but doesn't build now, and nothing has changed for this formula since 2015-05-10.

**Comment by sjackman** [comment] 2015-05-15 17:09
This time I got a different error. Perhaps it's due to a race condition that can be resolved with `ENV.deparallelize`.

```
/bin/sh ./libtool --tag=CC   --mode=link /gsc/btl/linuxbrew/bin/gcc-4.9 -D_REENTRANT=1 -DSQLITE_THREADSAFE=1  -DSQLITE_ENABLE_FTS3 -DSQLITE_ENABLE_RTREE -Os -w -pipe -march=core2  -L/gsc/btl/linuxbrew/lib -Wl,--dynamic-linker=/gsc/btl/linuxbrew/opt/glibc/lib/ld-linux-x86-64.so.2 -Wl,-rpath,/gsc/btl/linuxbrew/lib -o sqlite3 shell.o sqlite3.o -lreadline -lcurses  -ldl -lpthread 
libtool: link: /gsc/btl/linuxbrew/bin/gcc-4.9 -D_REENTRANT=1 -DSQLITE_THREADSAFE=1 -DSQLITE_ENABLE_FTS3 -DSQLITE_ENABLE_RTREE -Os -w -pipe -march=core2 -Wl,--dynamic-linker=/gsc/btl/linuxbrew/opt/glibc/lib/ld-linux-x86-64.so.2 -Wl,-rpath -Wl,/gsc/btl/linuxbrew/lib -o sqlite3 shell.o sqlite3.o  -L/gsc/btl/linuxbrew/lib -lreadline -lcurses -ldl -lpthread
gcc-4.9: error: sqlite3.o: No such file or directory
```

**Comment by saketkc** [comment] 2015-05-15 17:40
Yes.
```
--- a/Library/Formula/sqlite.rb
+++ b/Library/Formula/sqlite.rb
@@ -39,6 +39,7 @@ class Sqlite < Formula
   end
 
   def install
+    ENV.deparallelize

```
/home/saket/.linuxbrew/Cellar/sqlite/3.8.10.1: 9 files, 2.7M, built in 31 seconds

**Comment by sjackman** [comment] 2015-05-15 17:47
Oddly, this problem does not seem to affect Mac OS. At least it built successfully for me five times in a row.

**Comment by sjackman** [comment] 2015-05-15 17:55
Thanks for the bug reports. Fixed.

**Closed** 2015-05-15 17:55 UTC
Labels: build-error
