### ISSUE TITLE
homebrew/apache/httpd24 fails with "Error: Operation already in progress for zlib"

### ISSUE THREAD

**Issue by hannwong** [Homebrew/linuxbrew#505] opened 2015-08-09 03:42 UTC
Yikes! Pls mark this as duplicate. See #483.

The error message is:

    Error: Operation already in progress for zlib
    Another active Homebrew process is already using zlib.
    Please wait for it to finish or terminate it to continue.

**Comment by sjackman** [comment] 2015-08-09 23:41
Duplicate of #483.

**Closed by sjackman** 2015-08-09 23:41 UTC
Labels: duplicate
