### ISSUE TITLE
uninitialized constant OS_VERSION (NameError)

### ISSUE THREAD

**Issue by OmeGak** [Homebrew/linuxbrew#650] opened 2015-11-16 23:16 UTC
I'm trying to install Linuxbrew standalone following [this guide](https://github.com/Homebrew/linuxbrew/wiki/Standalone-Installation#ubuntu-1404-specific-tldr-setup-script) from the wiki on a clean Elementary OS Freya (Ubuntu 14.04) and I'm facing a problem early on in the process. This is the output I get every time I run `brew`.

```
$ brew doctor
/home/omegak/.linuxbrew/Library/Homebrew/global.rb:30:in `<top (required)>': uninitialized constant OS_VERSION (NameError)
	from /usr/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
	from /usr/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
	from /home/omegak/.linuxbrew/Library/brew.rb:15:in `<main>'
```

I don't know if it's relevant, but the Ruby version I have doesn't match what I get in the traceback.

```
$ ruby --version
ruby 1.9.3p484 (2013-11-22 revision 43786) [x86_64-linux]
```

 Am I missing anything?  It seems I'm the only person on the internet getting `"uninitialized constant OS_VERSION (NameError)"` when installing Linuxbrew. I took the same steps a few months back and worked just find, so I would say it's some kind of regression.

**Comment by naseer** [comment] 2015-11-16 23:21
Duplicate of #648

**Comment by DomT4** [comment] 2015-11-17 04:03
Working on it. Please track https://github.com/Homebrew/linuxbrew/issues/648, Thanks.

**Closed by DomT4** 2015-11-17 04:03 UTC

**Comment by DomT4** [comment] 2015-11-17 05:11
If `brew update` doesn't work you'll need to run:

```bash
git fetch && git reset --hard origin/master
```
Inside your Linuxbrew install to get `brew` functional again. Hopefully not many people updated over the last few hours. Sorry about this folks.
